/**
 * Copyright (c) 2017-present, Facebook, Inc.
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 */

module.exports = {
  // samples: {
  //   // Features: ["mdx"],
  //   "React 基础示例": [],
  // },
  skill: {
    简介: ["skill/introduction"],
    CSS: [
      "skill/css/css1",
      "skill/css/css2",
      "skill/css/css3",
      "skill/css/css4",
      "skill/css/css5",
      "skill/css/css6",
      "skill/css/css7",
      "skill/css/css8",
      "skill/css/css9",
      "skill/css/css11",
      "skill/css/css12",
    ],
    JavaScript: [
      "skill/js/js7",
      "skill/js/js2",
      "skill/js/js3",
      "skill/js/js5",
      "skill/js/js6",
      "skill/js/js9",
      "skill/js/js10",
      "skill/js/js8",
      "skill/es6/es01",
      "skill/es6/es02",
      "skill/es6/es03",
      "skill/es6/es04",
      "skill/es6/es05",
      {
        Promise: [
          "skill/es6/promise/promise1",
          "skill/es6/promise/promise2",
          "skill/es6/promise/promise3",
          "skill/es6/promise/promise4",
          "skill/es6/promise/async",
        ],
      },
      "skill/js/Array",
    ],
    React: [
      "skill/react/react01",
      "skill/react/react02",
      "skill/react/react03",
      "skill/react/react04",
      "skill/react/react05",
      "skill/react/react06",
      "skill/react/react07",
      "skill/react/react08",
      "skill/react/react09",
      "skill/react/react10",
      "skill/react/react",
      "skill/react/react11",
      "skill/react/react12",
      "skill/react/react13",
      "skill/react/react14",
      "skill/react/react15",
      "skill/react/react16",
      "skill/react/reactandvue",
      "skill/react/router_doc",
      "skill/react/router",
    ],
    Vue2: [
      "skill/vue/vue2/vue01",
      "skill/vue/vue2/vue02",
      "skill/vue/vue2/vue03",
      "skill/vue/vue2/vue04",
      "skill/vue/vue2/vue05",
      "skill/vue/vue2/vue06",
      "skill/vue/vue2/vue07",
      "skill/vue/vue2/vue08",
      "skill/vue/vue2/vue09",
      "skill/vue/vue2/vue10",
      "skill/vue/vue2/vue11",
      "skill/vue/vue2/vue12",
      "skill/vue/vue2/vue13",
      "skill/vue/vue2/vue14",
      "skill/vue/vue2/vue15",
      "skill/vue/vue2/vue16",
      "skill/vue/vue2/vue18",
      "skill/vue/vue2/vuers-1",
      "skill/vue/vue2/vuers-2",
      "skill/vue/vue2/vuers-3",
    ],
    Vue3: ["skill/vue/vue3/vue3-1"],

    TypeScript: [
      "skill/ts/ts1",
      "skill/ts/ts2",
      "skill/ts/ts3",
      "skill/ts/ts4",
      "skill/ts/ts5",
    ],
    微信小程序: [
      "skill/wechat/wechat",
      "skill/wechat/wechat2",
      "skill/wechat/wechat3",
      "skill/wechat/wechat4",
      "skill/wechat/wechat5",
      "skill/wechat/wechat6",
      "skill/wechat/wechat7",
      "skill/wechat/wechat8",
      "skill/wechat/wechat9",
      "skill/wechat/wechat10",
      "skill/wechat/wechat11",
      "skill/wechat/wechat12",
    ],
    HTTP: ["skill/http/http"],
    代码片段: [
      "skill/piece/js1",
      "skill/piece/js2",
      "skill/piece/css",
      "skill/piece/compatibility",
      "skill/piece/example",
      "skill/piece/html_string",
    ],
    数据结构与算法: ["skill/algorithm/introduction"],
    Webpack: [
      "skill/webpack/webpack1",
      "skill/webpack/webpack2",
      "skill/webpack/webpack3",
      "skill/webpack/webpack4",
    ],
    Git: ["skill/git/git-index", "skill/git/git-lint"],
    命名: ["skill/piece/namespace", "skill/piece/namespace2"],
  },
  interview: {
    简介: ["interview/introduction"],
    React: ["interview/react"],
    Vue: ["interview/vue"],
    TypeScript: ["interview/ts"],
    JavaScript: ["interview/js"],
    CSS: ["interview/css"],
    Webpack: ["interview/webpack"],
    性能优化: ["interview/perf"],
    Git操作: ["interview/git"],
    网络协议: ["interview/http"],
    移动端相关: ["interview/mobile"],
    工程化相关: ["interview/engineering"],
    计算机基础知识: ["interview/computer-base"],
    数据结构与算法: ["interview/algorithm"],
  },
};
